### ISSUE TITLE
Comments in Octave

### ISSUE THREAD

**Issue by coccoinomane** [textmate/matlab.tmbundle#7]
Hi! Syntax highlighting for Unix-like comments in Octave (hash comments) does not seem to work. Thanks, Guido

**Comment by infininight** [comment]
There are two grammars in this bundle, are you using the Octave grammar or the Matlab one? If you are using the Matlab one switch to Octave. If you are using Octave please include a sample code snippet that fails.

**Comment by coccoinomane** [comment]
Thank you infininight! The Octave grammar did not appear in the bottom bar menu until I closed & reopened Textmate; not it does, and it works fine. Thank you!
